// <auto-generated />
namespace IMS_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05081955 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05081955));
        
        string IMigrationMetadata.Id
        {
            get { return "201605080955350_05081955"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
